version: "3.9"

services:
  selenium:
    image: selenium/standalone-chrome

  parasite:
    build: 
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - selenium
    links:
      - selenium
    ports:
      - 3000:3000

  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
