version: "3.9"

services:
  selenium:
    image: selenium/standalone-chrome

  parasite:
    build: 
      context: .
      dockerfile: ./Dockerfile_parasite
    env_file:
      - .env
    depends_on:
      - selenium
    links:
      - selenium
    ports:
      - 3000:3000

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile_nginx
    image: nginx
    restart: always
    env_file:
      - .env
    environment:
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".conf"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

